### ISSUE TITLE
@artsy/fresnel compatibility issue

### ISSUE THREAD

**Issue by ha1fstack** [ha1fstack/soup-frontend#30]
Compatibility with React >=18:
see https://github.com/artsy/fresnel/issues/260

Compatibility with Next.js >12.1.5:
see https://github.com/artsy/fresnel/issues/280

**Comment by damassi** [comment]
@plrs9816 - React 18 support just landed for Fresnel! please install `@latest` and file an issue over in the repo if you run into  any issues.
